// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:5037/' | (string & {});
};

export type AssetLinkCategory = number;

export type AssetLinkType = 'StudyPlan' | 'Course' | 'Task' | 'Log';

export type AssetResponseDto = {
    id: number | string;
    fileName: string;
    publicId: string;
    url: string;
    extension: string;
    fileSize: number | string;
    type: FileType;
    createdAt: string;
    linkedType: AssetLinkType;
    category: AssetLinkCategory;
    formFieldKey: null | string;
};

export type BulkCreateStudyPlanDto = {
    studyPlans: Array<RequestStudyPlanDto>;
};

export type CalendarTaskDto = {
    id: number | string;
    title: string;
    startDate: string;
    startTime: string;
    endTime: string;
    location: null | string;
};

export type ChatDto = {
    prompt: string;
};

export type ChatHistoryDto = {
    id: number | string;
    role: string;
    content: string;
    data: null | string;
    type: string;
};

export type ComrehensiveLevel = number;

export type CourseStatus = 'Draft' | 'Enrolled' | 'Completed' | 'Dropped';

export type DayOfWeek = number;

export type DifficultyLevel = number;

export type EventRequirementReqDto = {
    name: string;
    expectedValue: number | string;
    unit: string;
    strategy: RequirementStrategy;
    timelineEventId: number | string;
};

export type EventRequirementResDto = {
    id: number | string;
    name: string;
    expectedValue: number | string;
    unit: string;
    strategy: RequirementStrategy;
    timelineEventId: number | string;
};

export type EventType = 'Exam' | 'Assignment' | 'Presentation' | 'ProjectDeadline' | 'Other';

export type FileType = number;

export type IFormFile = Blob | File;

export type IFormFileCollection = Array<IFormFile>;

export type LogDto = {
    id: number | string;
    note: null | string;
    actualDurationMinutes: null | number | string;
    productivityScore: null | number | string;
    comrehensiveLevel: null | ComrehensiveLevel;
    difficultyLevel: null | DifficultyLevel;
    timerStartAt: null | string;
    timerEndAt: null | string;
    eventRequirementId: null | number | string;
    earnedValue: null | number | string;
};

export type LoginResponseDto = {
    email?: string;
    userName?: string;
    fullName?: string;
    token: string;
    hasCompletedOnboarding?: boolean;
};

export type LogWorkDto = {
    note: null | string;
    actualDurationMinutes: null | number | string;
    productivityScore: null | number | string;
    comrehensiveLevel: null | ComrehensiveLevel;
    difficultyLevel: null | DifficultyLevel;
    timerStartAt: null | string;
    timerEndAt: null | string;
    eventRequirementId: null | number | string;
    earnedValue: null | number | string;
    assetIds: null | Array<number | string>;
    markAsCompleted: boolean;
};

export type PagedResultOfResponseSubjectDto = {
    items?: Array<ResponseSubjectDto>;
    totalCount?: number | string;
    pageIndex?: number | string;
    pageSize?: number | string;
    totalPages?: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PriorityLevel = number;

export type RequestCourseDto = {
    studyPlanId: number | string;
    subjectId: number | string;
    targetScore: null | number | string;
    finalScore: null | number | string;
    mentor: null | string;
    alternativeName: null | string;
};

export type RequestRoutineDto = {
    name: string;
    description: null | string;
    startDate: null | string;
    endDate: null | string;
    type: TaskType;
    courseId: null | number | string;
    eventRequirementId: null | number | string;
    studyPlanId: number | string;
};

export type RequestScheduleDto = {
    routineId: number | string;
    dayOfWeek: DayOfWeek;
    startTime: string;
    duration: number | string;
    durationUnit: TimeUnit;
    location: null | string;
};

export type RequestStudyPlanDto = {
    academicTermId: number | string;
    academicYearId: number | string;
    startDate: string;
    endDate: string;
};

export type RequestSubjectDto = {
    name: string;
    credits: number | string;
    type: SubjectType;
};

export type RequestTaskDto = {
    name: string;
    description: null | string;
    dueDate: null | string;
    startAt: null | string;
    endAt: null | string;
    type: TaskType;
    linkedFormIds: null | Array<number | string>;
    courseId: null | number | string;
    studyPlanId: number | string;
};

export type RequestTimelineEventDto = {
    courseId: number | string;
    title: string;
    dueDate: null | string;
    type: EventType;
    priority: PriorityLevel;
    location: null | string;
    notes: null | string;
};

export type RequirementStrategy = 'Additive' | 'Averaging' | 'MaxValue' | 'TaskBased';

export type ResponseCourseDto = {
    id: number | string;
    studyPlanId: number | string;
    subjectId: number | string;
    subjectName: string;
    mentor: null | string;
    alternativeName: null | string;
    credits: number | string;
    targetScore: null | number | string;
    finalScore: null | number | string;
    status: CourseStatus;
    timelineEvents: null | Array<ResponseTimelineEventDto>;
};

export type ResponseRoutineDto = {
    id: number | string;
    name: string;
    description: null | string;
    startDate: null | string;
    endDate: null | string;
    courseId: null | number | string;
    eventRequirementId: null | number | string;
    schedules: Array<ScheduleDto>;
    tasks: null | Array<ResponseTaskDto>;
};

export type ResponseScheduleDto = {
    id: number | string;
    routineId: number | string;
    dayOfWeek: DayOfWeek;
    startTime: null | string;
    duration: null | number | string;
    durationUnit: null | TimeUnit;
    location: null | string;
};

export type ResponseStudyPlanDto = {
    id: number | string;
    academicTermId: number | string;
    academicYearId: number | string;
    displayName: string;
    startDate: string;
    endDate: string;
    createdAt: string;
    updatedAt: null | string;
    status: StudyPlanStatus;
};

export type ResponseSubjectDto = {
    id: number | string;
    name: string;
    credits: number | string;
    type: SubjectType;
};

export type ResponseTaskDto = {
    id: number | string;
    name: string;
    description: null | string;
    dueDate: null | string;
    completedAt: null | string;
    startAt: null | string;
    endAt: null | string;
    type: TaskType;
    status: TaskStatus;
    logs: null | Array<LogDto>;
    routineId: null | number | string;
    scheduleId: null | number | string;
    courseId: number | string;
};

export type ResponseTimelineEventDto = {
    id: number | string;
    courseId: number | string;
    title: string;
    dueDate: string;
    type: EventType;
    priority: PriorityLevel;
    location: null | string;
    notes: null | string;
};

export type ScheduleDto = {
    id: number | string;
    dayOfWeek: DayOfWeek;
    startTime: string;
    duration: number | string;
    durationUnit: TimeUnit;
    location: null | string;
};

export type SessionDto = {
    title: string;
};

export type SessionResponseDto = {
    id: number | string;
    title: string;
};

export type SimpleResponseRoutineDto = {
    id: number | string;
    name: string;
    description: null | string;
    startDate: null | string;
    endDate: null | string;
    type: TaskType;
    courseId: null | number | string;
    eventRequirementId: null | number | string;
    schedules: Array<ScheduleDto>;
};

export type StudentInfoDto = {
    admissionDate: string;
    semestersPerYear: number | string;
    weeksPerSemester: number | string;
    weeksOfSummerSemester: null | number | string;
    programLength: number | string;
    university: null | string;
    major: null | string;
    cohort: null | string;
    totalRequiredCredits: null | number | string;
    creditsPerSemester: null | number | string;
    creditsPerSummerSemester: null | number | string;
};

export type StudyPlanStatus = 'Planning' | 'Active' | 'Completed';

export type SubjectType = 'Theory' | 'Practice' | 'Project' | 'Thesis';

export type TaskStatus = 'Pending' | 'InProgress' | 'Completed' | 'Cancelled';

export type TaskStatusDto = {
    status: TaskStatus;
};

export type TaskType = 'ClassSession' | 'SelfStudy' | 'AssignmentWork' | 'Meeting';

export type TimeUnit = 'Minutes' | 'Hours' | 'Periods';

export type UpdateCourseStatusDto = {
    status: CourseStatus;
};

export type UpdateScheduleDto = {
    dayOfWeek: DayOfWeek;
    startTime: string;
    duration: number | string;
    durationUnit: TimeUnit;
    location: null | string;
};

export type UpdateStudyPlanStatusDto = {
    status: StudyPlanStatus;
};

export type UserLoginDto = {
    userName: string;
    password: string;
};

export type UserRegisterDto = {
    email: string;
    password: string;
    userName: string;
    fullName: string;
};

export type UserResponseDto = {
    id?: number | string;
    email?: string;
    userName?: string;
    fullName?: string;
};

export type GetAssetsData = {
    body?: never;
    path?: never;
    query?: {
        linkedId?: number | string;
        linkedType?: AssetLinkType;
    };
    url: '/api/assets';
};

export type GetAssetsResponses = {
    /**
     * OK
     */
    200: Array<AssetResponseDto>;
};

export type GetAssetsResponse = GetAssetsResponses[keyof GetAssetsResponses];

export type UploadAssetsData = {
    body: {
        filepond?: IFormFileCollection;
    } & {
        linkedId?: number | string;
    } & {
        linkedType?: AssetLinkType;
    } & {
        category?: AssetLinkCategory;
    };
    path?: never;
    query?: never;
    url: '/api/assets';
};

export type UploadAssetsResponses = {
    /**
     * OK
     */
    200: Array<AssetResponseDto>;
};

export type UploadAssetsResponse = UploadAssetsResponses[keyof UploadAssetsResponses];

export type DeleteAssetData = {
    body?: never;
    path: {
        assetId: string;
    };
    query?: never;
    url: '/api/assets/{assetId}';
};

export type DeleteAssetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RegisterData = {
    body: UserRegisterDto;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: UserResponseDto;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: UserLoginDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: LoginResponseDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetProfileResponses = {
    /**
     * OK
     */
    200: UserResponseDto;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type GetCalendarData = {
    body?: never;
    path?: never;
    query?: {
        studyPlanId?: number | string;
        fromDate?: string;
        toDate?: string;
    };
    url: '/api/calendar';
};

export type GetCalendarResponses = {
    /**
     * OK
     */
    200: Array<CalendarTaskDto>;
};

export type GetCalendarResponse = GetCalendarResponses[keyof GetCalendarResponses];

export type GetChatSessionByIdData = {
    body?: never;
    path: {
        sessionId: number | string;
    };
    query?: never;
    url: '/api/Chat/sessions/{sessionId}';
};

export type GetChatSessionByIdResponses = {
    /**
     * OK
     */
    200: Array<ChatHistoryDto>;
};

export type GetChatSessionByIdResponse = GetChatSessionByIdResponses[keyof GetChatSessionByIdResponses];

export type GetAllChatSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Chat/sessions';
};

export type GetAllChatSessionsResponses = {
    /**
     * OK
     */
    200: Array<SessionResponseDto>;
};

export type GetAllChatSessionsResponse = GetAllChatSessionsResponses[keyof GetAllChatSessionsResponses];

export type CreateChatSessionData = {
    body: SessionDto;
    path?: never;
    query?: never;
    url: '/api/Chat/sessions';
};

export type CreateChatSessionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiChatSessionsBySessionIdStreamData = {
    body: ChatDto;
    path: {
        sessionId: number | string;
    };
    query?: never;
    url: '/api/Chat/sessions/{sessionId}/stream';
};

export type PostApiChatSessionsBySessionIdStreamResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCoursesByStudyPlanData = {
    body?: never;
    path: {
        studyPlanId: number;
    };
    query?: never;
    url: '/api/courses/study-plan/{studyPlanId}';
};

export type GetCoursesByStudyPlanResponses = {
    /**
     * OK
     */
    200: Array<ResponseCourseDto>;
};

export type GetCoursesByStudyPlanResponse = GetCoursesByStudyPlanResponses[keyof GetCoursesByStudyPlanResponses];

export type DeleteCourseData = {
    body?: never;
    path: {
        courseId: number | string;
    };
    query?: never;
    url: '/api/courses/{courseId}';
};

export type DeleteCourseResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCourseByIdData = {
    body?: never;
    path: {
        courseId: number | string;
    };
    query?: never;
    url: '/api/courses/{courseId}';
};

export type GetCourseByIdResponses = {
    /**
     * OK
     */
    200: ResponseCourseDto;
};

export type GetCourseByIdResponse = GetCourseByIdResponses[keyof GetCourseByIdResponses];

export type UpdateCourseData = {
    body: RequestCourseDto;
    path: {
        courseId: number | string;
    };
    query?: never;
    url: '/api/courses/{courseId}';
};

export type UpdateCourseResponses = {
    /**
     * OK
     */
    200: ResponseCourseDto;
};

export type UpdateCourseResponse = UpdateCourseResponses[keyof UpdateCourseResponses];

export type CreateCourseData = {
    body: RequestCourseDto;
    path?: never;
    query?: never;
    url: '/api/courses';
};

export type CreateCourseResponses = {
    /**
     * OK
     */
    200: ResponseCourseDto;
};

export type CreateCourseResponse = CreateCourseResponses[keyof CreateCourseResponses];

export type UpdateCourseStatusData = {
    body: UpdateCourseStatusDto;
    path: {
        courseId: number;
    };
    query?: never;
    url: '/api/courses/{courseId}/status';
};

export type UpdateCourseStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteLogData = {
    body?: never;
    path: {
        taskLogId: number | string;
    };
    query?: never;
    url: '/api/logs/{taskLogId}';
};

export type DeleteLogResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetLogData = {
    body?: never;
    path: {
        taskLogId: number | string;
    };
    query?: never;
    url: '/api/logs/{taskLogId}';
};

export type GetLogResponses = {
    /**
     * OK
     */
    200: LogDto;
};

export type GetLogResponse = GetLogResponses[keyof GetLogResponses];

export type UpdateLogData = {
    body: LogDto;
    path: {
        taskLogId: number | string;
    };
    query?: never;
    url: '/api/logs/{taskLogId}';
};

export type UpdateLogResponses = {
    /**
     * OK
     */
    200: LogDto;
};

export type UpdateLogResponse = UpdateLogResponses[keyof UpdateLogResponses];

export type DeleteRoutineData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/routines/{id}';
};

export type DeleteRoutineResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRoutineByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/routines/{id}';
};

export type GetRoutineByIdResponses = {
    /**
     * OK
     */
    200: ResponseRoutineDto;
};

export type GetRoutineByIdResponse = GetRoutineByIdResponses[keyof GetRoutineByIdResponses];

export type UpdateRoutineData = {
    body: RequestRoutineDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/routines/{id}';
};

export type UpdateRoutineResponses = {
    /**
     * OK
     */
    200: ResponseRoutineDto;
};

export type UpdateRoutineResponse = UpdateRoutineResponses[keyof UpdateRoutineResponses];

export type GetRoutinesData = {
    body?: never;
    path?: never;
    query?: {
        StudyPlanId?: number | string;
        CourseId?: number | string;
        Type?: TaskType;
    };
    url: '/api/routines';
};

export type GetRoutinesResponses = {
    /**
     * OK
     */
    200: Array<SimpleResponseRoutineDto>;
};

export type GetRoutinesResponse = GetRoutinesResponses[keyof GetRoutinesResponses];

export type CreateRoutineData = {
    body: RequestRoutineDto;
    path?: never;
    query?: never;
    url: '/api/routines';
};

export type CreateRoutineResponses = {
    /**
     * OK
     */
    200: ResponseRoutineDto;
};

export type CreateRoutineResponse = CreateRoutineResponses[keyof CreateRoutineResponses];

export type GenerateTasksData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: {
        upToDate?: string;
    };
    url: '/api/routines/{id}/generate-tasks';
};

export type GenerateTasksResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUpcomingRoutineTasksData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: {
        daysAhead?: number | string;
    };
    url: '/api/routines/{id}/upcoming-tasks';
};

export type GetUpcomingRoutineTasksResponses = {
    /**
     * OK
     */
    200: Array<ResponseTaskDto>;
};

export type GetUpcomingRoutineTasksResponse = GetUpcomingRoutineTasksResponses[keyof GetUpcomingRoutineTasksResponses];

export type CreateScheduleData = {
    body: RequestScheduleDto;
    path?: never;
    query?: never;
    url: '/api/schedules';
};

export type CreateScheduleResponses = {
    /**
     * OK
     */
    200: ResponseScheduleDto;
};

export type CreateScheduleResponse = CreateScheduleResponses[keyof CreateScheduleResponses];

export type DeleteScheduleData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/schedules/{id}';
};

export type DeleteScheduleResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateScheduleData = {
    body: UpdateScheduleDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/schedules/{id}';
};

export type UpdateScheduleResponses = {
    /**
     * OK
     */
    200: ResponseScheduleDto;
};

export type UpdateScheduleResponse = UpdateScheduleResponses[keyof UpdateScheduleResponses];

export type GetStudyPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/study-plans';
};

export type GetStudyPlansResponses = {
    /**
     * OK
     */
    200: Array<ResponseStudyPlanDto>;
};

export type GetStudyPlansResponse = GetStudyPlansResponses[keyof GetStudyPlansResponses];

export type CreateStudyPlanData = {
    body: RequestStudyPlanDto;
    path?: never;
    query?: never;
    url: '/api/study-plans';
};

export type CreateStudyPlanResponses = {
    /**
     * OK
     */
    200: ResponseStudyPlanDto;
};

export type CreateStudyPlanResponse = CreateStudyPlanResponses[keyof CreateStudyPlanResponses];

export type BulkCreateStudyPlansData = {
    body: BulkCreateStudyPlanDto;
    path?: never;
    query?: never;
    url: '/api/study-plans/bulk';
};

export type BulkCreateStudyPlansResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteStudyPlanData = {
    body?: never;
    path: {
        studyPlanId: number;
    };
    query?: never;
    url: '/api/study-plans/{studyPlanId}';
};

export type DeleteStudyPlanResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetStudyPlanByIdData = {
    body?: never;
    path: {
        studyPlanId: number;
    };
    query?: never;
    url: '/api/study-plans/{studyPlanId}';
};

export type GetStudyPlanByIdResponses = {
    /**
     * OK
     */
    200: ResponseStudyPlanDto;
};

export type GetStudyPlanByIdResponse = GetStudyPlanByIdResponses[keyof GetStudyPlanByIdResponses];

export type UpdateStudyPlanData = {
    body: RequestStudyPlanDto;
    path: {
        studyPlanId: number;
    };
    query?: never;
    url: '/api/study-plans/{studyPlanId}';
};

export type UpdateStudyPlanResponses = {
    /**
     * OK
     */
    200: ResponseStudyPlanDto;
};

export type UpdateStudyPlanResponse = UpdateStudyPlanResponses[keyof UpdateStudyPlanResponses];

export type UpdateStudyPlanStatusData = {
    body: UpdateStudyPlanStatusDto;
    path: {
        planId: number;
    };
    query?: never;
    url: '/api/study-plans/{planId}/status';
};

export type UpdateStudyPlanStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetSubjectsData = {
    body?: never;
    path?: never;
    query?: {
        PageIndex?: number | string;
        PageSize?: number | string;
        SearchTerm?: string;
    };
    url: '/api/subjects';
};

export type GetSubjectsResponses = {
    /**
     * OK
     */
    200: PagedResultOfResponseSubjectDto;
};

export type GetSubjectsResponse = GetSubjectsResponses[keyof GetSubjectsResponses];

export type CreateSubjectData = {
    body: RequestSubjectDto;
    path?: never;
    query?: never;
    url: '/api/subjects';
};

export type CreateSubjectResponses = {
    /**
     * OK
     */
    200: ResponseSubjectDto;
};

export type CreateSubjectResponse = CreateSubjectResponses[keyof CreateSubjectResponses];

export type BulkCreateSubjectsData = {
    body: Array<RequestSubjectDto>;
    path?: never;
    query?: never;
    url: '/api/subjects/bulk';
};

export type BulkCreateSubjectsResponses = {
    /**
     * OK
     */
    200: Array<ResponseSubjectDto>;
};

export type BulkCreateSubjectsResponse = BulkCreateSubjectsResponses[keyof BulkCreateSubjectsResponses];

export type DeleteSubjectData = {
    body?: never;
    path: {
        subjectId: number;
    };
    query?: never;
    url: '/api/subjects/{subjectId}';
};

export type DeleteSubjectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateSubjectData = {
    body: RequestSubjectDto;
    path: {
        subjectId: number;
    };
    query?: never;
    url: '/api/subjects/{subjectId}';
};

export type UpdateSubjectResponses = {
    /**
     * OK
     */
    200: ResponseSubjectDto;
};

export type UpdateSubjectResponse = UpdateSubjectResponses[keyof UpdateSubjectResponses];

export type GetTasksData = {
    body?: never;
    path?: never;
    query?: {
        fromDate?: string;
        toDate?: string;
        studyPlanId?: number | string;
    };
    url: '/api/tasks';
};

export type GetTasksResponses = {
    /**
     * OK
     */
    200: Array<ResponseTaskDto>;
};

export type GetTasksResponse = GetTasksResponses[keyof GetTasksResponses];

export type CreateTaskData = {
    body: RequestTaskDto;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type CreateTaskResponses = {
    /**
     * OK
     */
    200: ResponseTaskDto;
};

export type CreateTaskResponse = CreateTaskResponses[keyof CreateTaskResponses];

export type DeleteTaskByIdData = {
    body?: never;
    path: {
        taskId: number | string;
    };
    query?: never;
    url: '/api/tasks/{taskId}';
};

export type DeleteTaskByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTaskByIdData = {
    body?: never;
    path: {
        taskId: number | string;
    };
    query?: never;
    url: '/api/tasks/{taskId}';
};

export type GetTaskByIdResponses = {
    /**
     * OK
     */
    200: ResponseTaskDto;
};

export type GetTaskByIdResponse = GetTaskByIdResponses[keyof GetTaskByIdResponses];

export type UpdateTaskInfoData = {
    body: RequestTaskDto;
    path: {
        taskId: number | string;
    };
    query?: never;
    url: '/api/tasks/{taskId}';
};

export type UpdateTaskInfoResponses = {
    /**
     * OK
     */
    200: ResponseTaskDto;
};

export type UpdateTaskInfoResponse = UpdateTaskInfoResponses[keyof UpdateTaskInfoResponses];

export type UpdateTaskStatusData = {
    body: TaskStatusDto;
    path: {
        taskId: number | string;
    };
    query?: never;
    url: '/api/tasks/{taskId}/status';
};

export type UpdateTaskStatusResponses = {
    /**
     * OK
     */
    200: ResponseTaskDto;
};

export type UpdateTaskStatusResponse = UpdateTaskStatusResponses[keyof UpdateTaskStatusResponses];

export type CreateTaskLogWorkData = {
    body: LogWorkDto;
    path: {
        taskId: number | string;
    };
    query?: never;
    url: '/api/tasks/{taskId}/logs';
};

export type CreateTaskLogWorkResponses = {
    /**
     * OK
     */
    200: ResponseTaskDto;
};

export type CreateTaskLogWorkResponse = CreateTaskLogWorkResponses[keyof CreateTaskLogWorkResponses];

export type CreateEventData = {
    body: RequestTimelineEventDto;
    path?: never;
    query?: never;
    url: '/api/events';
};

export type CreateEventResponses = {
    /**
     * OK
     */
    200: ResponseTimelineEventDto;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type GetEventsByCourseData = {
    body?: never;
    path: {
        courseId: number;
    };
    query?: never;
    url: '/api/events/course/{courseId}';
};

export type GetEventsByCourseResponses = {
    /**
     * OK
     */
    200: Array<ResponseTimelineEventDto>;
};

export type GetEventsByCourseResponse = GetEventsByCourseResponses[keyof GetEventsByCourseResponses];

export type DeleteEventData = {
    body?: never;
    path: {
        timelineEventId: number;
    };
    query?: never;
    url: '/api/events/{timelineEventId}';
};

export type DeleteEventResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateEventData = {
    body: RequestTimelineEventDto;
    path: {
        timelineEventId: number;
    };
    query?: never;
    url: '/api/events/{timelineEventId}';
};

export type UpdateEventResponses = {
    /**
     * OK
     */
    200: ResponseTimelineEventDto;
};

export type UpdateEventResponse = UpdateEventResponses[keyof UpdateEventResponses];

export type GetEventRequirementsData = {
    body?: never;
    path: {
        eventId: number | string;
    };
    query?: never;
    url: '/api/events/{eventId}/requirements';
};

export type GetEventRequirementsResponses = {
    /**
     * OK
     */
    200: Array<EventRequirementResDto>;
};

export type GetEventRequirementsResponse = GetEventRequirementsResponses[keyof GetEventRequirementsResponses];

export type CreateEvenetRequirementData = {
    body: EventRequirementReqDto;
    path: {
        eventId: number | string;
    };
    query?: never;
    url: '/api/events/{eventId}/requirements';
};

export type CreateEvenetRequirementResponses = {
    /**
     * OK
     */
    200: ResponseTimelineEventDto;
};

export type CreateEvenetRequirementResponse = CreateEvenetRequirementResponses[keyof CreateEvenetRequirementResponses];

export type DeleteEventRequirementData = {
    body?: never;
    path: {
        requirementId: number | string;
    };
    query?: never;
    url: '/api/events/requirements/{requirementId}';
};

export type DeleteEventRequirementResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateEventRequirementData = {
    body: EventRequirementReqDto;
    path: {
        requirementId: number | string;
    };
    query?: never;
    url: '/api/events/requirements/{requirementId}';
};

export type UpdateEventRequirementResponses = {
    /**
     * OK
     */
    200: EventRequirementResDto;
};

export type UpdateEventRequirementResponse = UpdateEventRequirementResponses[keyof UpdateEventRequirementResponses];

export type PatchApiUsersSettingStudentInfoData = {
    body: StudentInfoDto;
    path?: never;
    query?: never;
    url: '/api/users/setting/student-info';
};

export type PatchApiUsersSettingStudentInfoResponses = {
    /**
     * OK
     */
    200: unknown;
};
