// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:5037/' | (string & {});
};

export type AssetLinkCategory = number;

export type AssetLinkType = number;

export type AssetResponseDto = {
    id: number | string;
    fileName: string;
    publicId: string;
    url: string;
    extension: string;
    fileSize: number | string;
    type: FileType;
    createdAt: string;
    linkedType: AssetLinkType;
    category: AssetLinkCategory;
    formFieldKey: null | string;
};

export type ChatDto = {
    prompt: string;
};

export type ComrehensiveLevel = number;

export type DayOfWeek = number;

export type DifficultyLevel = number;

export type EventRequirementReqDto = {
    name: string;
    expectedValue: number | string;
    unit: string;
    strategy: RequirementStrategy;
    timelineEventId: number | string;
};

export type EventRequirementResDto = {
    id: number | string;
    name: string;
    expectedValue: number | string;
    unit: string;
    strategy: RequirementStrategy;
    timelineEventId: number | string;
};

export type EventType = 'Exam' | 'Assignment' | 'Presentation' | 'ProjectDeadline' | 'Other';

export type FileType = number;

export type Frequency = 'Daily' | 'Weekly' | 'Monthly' | 'Yearly';

export type IFormFile = Blob | File;

export type LogDto = {
    id: number | string;
    note: null | string;
    actualDurationMinutes: null | number | string;
    productivityScore: null | number | string;
    comrehensiveLevel: null | ComrehensiveLevel;
    difficultyLevel: null | DifficultyLevel;
    timerStartAt: null | string;
    timerEndAt: null | string;
    eventRequirementId: null | number | string;
    earnedValue: null | number | string;
};

export type LoginResponseDto = {
    email?: string;
    userName?: string;
    fullName?: string;
    token: string;
};

export type LogWorkDto = {
    note: null | string;
    actualDurationMinutes: null | number | string;
    productivityScore: null | number | string;
    comrehensiveLevel: null | ComrehensiveLevel;
    difficultyLevel: null | DifficultyLevel;
    timerStartAt: null | string;
    timerEndAt: null | string;
    eventRequirementId: null | number | string;
    earnedValue: null | number | string;
    assetIds: null | Array<number | string>;
    markAsCompleted: boolean;
};

export type PagedResultOfResponseSubjectDto = {
    items?: Array<ResponseSubjectDto>;
    totalCount?: number | string;
    pageIndex?: number | string;
    pageSize?: number | string;
    totalPages?: number | string;
    hasPreviousPage?: boolean;
    hasNextPage?: boolean;
};

export type PriorityLevel = number;

export type RequestCourseDto = {
    studyPlanId: number | string;
    subjectId: number | string;
    targetScore: null | number | string;
    finalScore: null | number | string;
};

export type RequestRoutineDto = {
    id: number | string;
    name: string;
    description: null | string;
    startDate: null | string;
    endDate: null | string;
    type: TaskType;
    courseId: null | number | string;
    eventRequirementId: null | number | string;
    schedules: null | Array<ScheduleDto>;
};

export type RequestStudyPlanDto = {
    academicTermId: number | string;
    academicYearId: number | string;
    startDate: string;
    endDate: string;
};

export type RequestSubjectDto = {
    name: string;
    credits: number | string;
    type: SubjectType;
};

export type RequestTaskDto = {
    name: string;
    description: null | string;
    dueDate: null | string;
    startAt: null | string;
    endAt: null | string;
    type: TaskType;
    linkedFormIds: null | Array<number | string>;
    courseId: null | number | string;
};

export type RequestTimelineEventDto = {
    courseId: number | string;
    title: string;
    dueDate: null | string;
    type: EventType;
    priority: PriorityLevel;
    location: null | string;
    notes: null | string;
};

export type RequirementStrategy = 'Additive' | 'Averaging' | 'MaxValue' | 'TaskBased';

export type ResponseCourseDto = {
    id: number | string;
    studyPlanId: number | string;
    subjectId: number | string;
    subjectName: string;
    credits: number | string;
    targetScore: null | number | string;
    finalScore: null | number | string;
};

export type ResponseRoutineDto = {
    id: number | string;
    name: string;
    description: null | string;
    startDate: null | string;
    endDate: null | string;
    courseId: null | number | string;
    eventRequirementId: null | number | string;
    schedules: Array<ScheduleDto>;
    tasks: null | Array<ResponseTaskDto>;
};

export type ResponseStudyPlanDto = {
    id: number | string;
    academicTermId: number | string;
    academicYearId: number | string;
    displayName: string;
    startDate: string;
    endDate: string;
    createdAt: string;
    updatedAt: null | string;
    status: StudyPlanStatus;
};

export type ResponseSubjectDto = {
    id: number | string;
    name: string;
    credits: number | string;
    type: SubjectType;
};

export type ResponseTaskDto = {
    id: number | string;
    name: string;
    description: null | string;
    dueDate: null | string;
    completedAt: null | string;
    startAt: null | string;
    endAt: null | string;
    type: TaskType;
    status: TaskStatus;
    logs: null | Array<LogDto>;
    routineId: null | number | string;
    scheduleId: null | number | string;
    courseId: number | string;
};

export type ResponseTimelineEventDto = {
    id: number | string;
    courseId: number | string;
    title: string;
    dueDate: string;
    type: EventType;
    priority: PriorityLevel;
    location: null | string;
    notes: null | string;
};

export type ScheduleDto = {
    id: number | string;
    frequency: Frequency;
    interval: number | string;
    dayOfWeek: DayOfWeek;
    daysOfMonth: null | Array<number | string>;
    startTime: string;
    duration: number | string;
    durationUnit: TimeUnit;
    location: null | string;
};

export type SessionDto = {
    title: string;
    semesterId: null | number | string;
};

export type SimpleResponseCourseDto = {
    id: number | string;
    subjectId: number | string;
    subjectName: string;
    credits: number | string;
    targetScore: null | number | string;
    finalScore: null | number | string;
};

export type StudyPlanStatus = 'Past' | 'Active' | 'Future';

export type SubjectType = 'Theory' | 'Practice' | 'Project' | 'Thesis';

export type TaskStatus = 'Pending' | 'InProgress' | 'Completed' | 'Cancelled';

export type TaskStatusDto = {
    status: TaskStatus;
};

export type TaskType = 'ClassSession' | 'SelfStudy' | 'AssignmentWork' | 'LifeHabit';

export type TimeUnit = 'Minutes' | 'Hours' | 'Periods';

export type UserLoginDto = {
    userName: string;
    password: string;
};

export type UserRegisterDto = {
    email: string;
    password: string;
    userName: string;
    fullName: string;
};

export type UserResponseDto = {
    id?: number | string;
    email?: string;
    userName?: string;
    fullName?: string;
};

export type UserSettingDto = {
    admissionDate: string;
    semestersPerYear: number | string;
    weeksPerSemester: number | string;
    weeksOfSummerSemester: null | number | string;
    programLength: number | string;
    studyPlans: Array<RequestStudyPlanDto>;
};

export type GetAssetsData = {
    body?: never;
    path?: never;
    query?: {
        linkedId?: number | string;
        linkedType?: AssetLinkType;
    };
    url: '/api/assets';
};

export type GetAssetsResponses = {
    /**
     * OK
     */
    200: Array<AssetResponseDto>;
};

export type GetAssetsResponse = GetAssetsResponses[keyof GetAssetsResponses];

export type UploadAssetsData = {
    body: {
        Files?: Array<IFormFile>;
        LinkedId?: number | string;
        LinkedType?: AssetLinkType;
        Category?: AssetLinkCategory;
        FormFieldKey?: string;
    };
    path?: never;
    query?: never;
    url: '/api/assets';
};

export type UploadAssetsResponses = {
    /**
     * OK
     */
    200: Array<AssetResponseDto>;
};

export type UploadAssetsResponse = UploadAssetsResponses[keyof UploadAssetsResponses];

export type DeleteAssetData = {
    body?: never;
    path: {
        assetId: string;
    };
    query?: never;
    url: '/api/assets/{assetId}';
};

export type DeleteAssetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RegisterData = {
    body: UserRegisterDto;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: UserResponseDto;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: UserLoginDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: LoginResponseDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetProfileResponses = {
    /**
     * OK
     */
    200: UserResponseDto;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type GetApiChatSessionsBySessionIdData = {
    body?: never;
    path: {
        sessionId: number | string;
    };
    query?: never;
    url: '/api/Chat/sessions/{sessionId}';
};

export type GetApiChatSessionsBySessionIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiChatSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Chat/sessions';
};

export type GetApiChatSessionsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiChatSessionsData = {
    body: SessionDto;
    path?: never;
    query?: never;
    url: '/api/Chat/sessions';
};

export type PostApiChatSessionsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiChatSessionsBySessionIdStreamData = {
    body: ChatDto;
    path: {
        sessionId: number | string;
    };
    query?: never;
    url: '/api/Chat/sessions/{sessionId}/stream';
};

export type PostApiChatSessionsBySessionIdStreamResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCoursesByStudyPlanData = {
    body?: never;
    path: {
        studyPlanId: number;
    };
    query?: never;
    url: '/api/courses/study-plan/{studyPlanId}';
};

export type GetCoursesByStudyPlanResponses = {
    /**
     * OK
     */
    200: Array<SimpleResponseCourseDto>;
};

export type GetCoursesByStudyPlanResponse = GetCoursesByStudyPlanResponses[keyof GetCoursesByStudyPlanResponses];

export type DeleteCourseData = {
    body?: never;
    path: {
        courseId: number | string;
    };
    query?: never;
    url: '/api/courses/{courseId}';
};

export type DeleteCourseResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCourseByIdData = {
    body?: never;
    path: {
        courseId: number | string;
    };
    query?: never;
    url: '/api/courses/{courseId}';
};

export type GetCourseByIdResponses = {
    /**
     * OK
     */
    200: ResponseCourseDto;
};

export type GetCourseByIdResponse = GetCourseByIdResponses[keyof GetCourseByIdResponses];

export type UpdateCourseData = {
    body: RequestCourseDto;
    path: {
        courseId: number | string;
    };
    query?: never;
    url: '/api/courses/{courseId}';
};

export type UpdateCourseResponses = {
    /**
     * OK
     */
    200: ResponseCourseDto;
};

export type UpdateCourseResponse = UpdateCourseResponses[keyof UpdateCourseResponses];

export type CreateCourseData = {
    body: RequestCourseDto;
    path?: never;
    query?: never;
    url: '/api/courses';
};

export type CreateCourseResponses = {
    /**
     * OK
     */
    200: ResponseCourseDto;
};

export type CreateCourseResponse = CreateCourseResponses[keyof CreateCourseResponses];

export type DeleteLogData = {
    body?: never;
    path: {
        taskLogId: number | string;
    };
    query?: never;
    url: '/api/logs/{taskLogId}';
};

export type DeleteLogResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetLogData = {
    body?: never;
    path: {
        taskLogId: number | string;
    };
    query?: never;
    url: '/api/logs/{taskLogId}';
};

export type GetLogResponses = {
    /**
     * OK
     */
    200: LogDto;
};

export type GetLogResponse = GetLogResponses[keyof GetLogResponses];

export type UpdateLogData = {
    body: LogDto;
    path: {
        taskLogId: number | string;
    };
    query?: never;
    url: '/api/logs/{taskLogId}';
};

export type UpdateLogResponses = {
    /**
     * OK
     */
    200: LogDto;
};

export type UpdateLogResponse = UpdateLogResponses[keyof UpdateLogResponses];

export type DeleteRoutineData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/routines/{id}';
};

export type DeleteRoutineResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRoutineByIdData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/routines/{id}';
};

export type GetRoutineByIdResponses = {
    /**
     * OK
     */
    200: ResponseRoutineDto;
};

export type GetRoutineByIdResponse = GetRoutineByIdResponses[keyof GetRoutineByIdResponses];

export type UpdateRoutineData = {
    body: RequestRoutineDto;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/routines/{id}';
};

export type UpdateRoutineResponses = {
    /**
     * OK
     */
    200: ResponseRoutineDto;
};

export type UpdateRoutineResponse = UpdateRoutineResponses[keyof UpdateRoutineResponses];

export type GetRoutinesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/routines';
};

export type GetRoutinesResponses = {
    /**
     * OK
     */
    200: Array<ResponseRoutineDto>;
};

export type GetRoutinesResponse = GetRoutinesResponses[keyof GetRoutinesResponses];

export type CreateRoutineData = {
    body: RequestRoutineDto;
    path?: never;
    query?: never;
    url: '/api/routines';
};

export type CreateRoutineResponses = {
    /**
     * OK
     */
    200: ResponseRoutineDto;
};

export type CreateRoutineResponse = CreateRoutineResponses[keyof CreateRoutineResponses];

export type GenerateTasksData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: {
        upToDate?: string;
    };
    url: '/api/routines/{id}/generate-tasks';
};

export type GenerateTasksResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUpcomingRoutineTasksData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: {
        daysAhead?: number | string;
    };
    url: '/api/routines/{id}/upcoming-tasks';
};

export type GetUpcomingRoutineTasksResponses = {
    /**
     * OK
     */
    200: Array<ResponseTaskDto>;
};

export type GetUpcomingRoutineTasksResponse = GetUpcomingRoutineTasksResponses[keyof GetUpcomingRoutineTasksResponses];

export type GetStudyPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/study-plans';
};

export type GetStudyPlansResponses = {
    /**
     * OK
     */
    200: Array<ResponseStudyPlanDto>;
};

export type GetStudyPlansResponse = GetStudyPlansResponses[keyof GetStudyPlansResponses];

export type CreateStudyPlanData = {
    body: RequestStudyPlanDto;
    path?: never;
    query?: never;
    url: '/api/study-plans';
};

export type CreateStudyPlanResponses = {
    /**
     * OK
     */
    200: ResponseStudyPlanDto;
};

export type CreateStudyPlanResponse = CreateStudyPlanResponses[keyof CreateStudyPlanResponses];

export type DeleteStudyPlanData = {
    body?: never;
    path: {
        studyPlanId: number;
    };
    query?: never;
    url: '/api/study-plans/{studyPlanId}';
};

export type DeleteStudyPlanResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetStudyPlanByIdData = {
    body?: never;
    path: {
        studyPlanId: number;
    };
    query?: never;
    url: '/api/study-plans/{studyPlanId}';
};

export type GetStudyPlanByIdResponses = {
    /**
     * OK
     */
    200: ResponseStudyPlanDto;
};

export type GetStudyPlanByIdResponse = GetStudyPlanByIdResponses[keyof GetStudyPlanByIdResponses];

export type UpdateStudyPlanData = {
    body: RequestStudyPlanDto;
    path: {
        studyPlanId: number;
    };
    query?: never;
    url: '/api/study-plans/{studyPlanId}';
};

export type UpdateStudyPlanResponses = {
    /**
     * OK
     */
    200: ResponseStudyPlanDto;
};

export type UpdateStudyPlanResponse = UpdateStudyPlanResponses[keyof UpdateStudyPlanResponses];

export type GetSubjectsData = {
    body?: never;
    path?: never;
    query?: {
        PageIndex?: number | string;
        PageSize?: number | string;
        SearchTerm?: string;
    };
    url: '/api/subjects';
};

export type GetSubjectsResponses = {
    /**
     * OK
     */
    200: PagedResultOfResponseSubjectDto;
};

export type GetSubjectsResponse = GetSubjectsResponses[keyof GetSubjectsResponses];

export type CreateSubjectData = {
    body: RequestSubjectDto;
    path?: never;
    query?: never;
    url: '/api/subjects';
};

export type CreateSubjectResponses = {
    /**
     * OK
     */
    200: ResponseSubjectDto;
};

export type CreateSubjectResponse = CreateSubjectResponses[keyof CreateSubjectResponses];

export type BulkCreateSubjectsData = {
    body: Array<RequestSubjectDto>;
    path?: never;
    query?: never;
    url: '/api/subjects/bulk';
};

export type BulkCreateSubjectsResponses = {
    /**
     * OK
     */
    200: Array<ResponseSubjectDto>;
};

export type BulkCreateSubjectsResponse = BulkCreateSubjectsResponses[keyof BulkCreateSubjectsResponses];

export type DeleteSubjectData = {
    body?: never;
    path: {
        subjectId: number;
    };
    query?: never;
    url: '/api/subjects/{subjectId}';
};

export type DeleteSubjectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateSubjectData = {
    body: RequestSubjectDto;
    path: {
        subjectId: number;
    };
    query?: never;
    url: '/api/subjects/{subjectId}';
};

export type UpdateSubjectResponses = {
    /**
     * OK
     */
    200: ResponseSubjectDto;
};

export type UpdateSubjectResponse = UpdateSubjectResponses[keyof UpdateSubjectResponses];

export type PostApiTasksData = {
    body: RequestTaskDto;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type PostApiTasksResponses = {
    /**
     * OK
     */
    200: ResponseTaskDto;
};

export type PostApiTasksResponse = PostApiTasksResponses[keyof PostApiTasksResponses];

export type DeleteApiTasksByTaskIdData = {
    body?: never;
    path: {
        taskId: number | string;
    };
    query?: never;
    url: '/api/tasks/{taskId}';
};

export type DeleteApiTasksByTaskIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTasksByTaskIdData = {
    body?: never;
    path: {
        taskId: number | string;
    };
    query?: never;
    url: '/api/tasks/{taskId}';
};

export type GetApiTasksByTaskIdResponses = {
    /**
     * OK
     */
    200: ResponseTaskDto;
};

export type GetApiTasksByTaskIdResponse = GetApiTasksByTaskIdResponses[keyof GetApiTasksByTaskIdResponses];

export type UpdateTaskInfoData = {
    body: RequestTaskDto;
    path: {
        taskId: number | string;
    };
    query?: never;
    url: '/api/tasks/{taskId}';
};

export type UpdateTaskInfoResponses = {
    /**
     * OK
     */
    200: ResponseTaskDto;
};

export type UpdateTaskInfoResponse = UpdateTaskInfoResponses[keyof UpdateTaskInfoResponses];

export type PatchApiTasksByTaskIdStatusData = {
    body: TaskStatusDto;
    path: {
        taskId: number | string;
    };
    query?: never;
    url: '/api/tasks/{taskId}/status';
};

export type PatchApiTasksByTaskIdStatusResponses = {
    /**
     * OK
     */
    200: ResponseTaskDto;
};

export type PatchApiTasksByTaskIdStatusResponse = PatchApiTasksByTaskIdStatusResponses[keyof PatchApiTasksByTaskIdStatusResponses];

export type PostApiTasksByTaskIdLogsData = {
    body: LogWorkDto;
    path: {
        taskId: number | string;
    };
    query?: never;
    url: '/api/tasks/{taskId}/logs';
};

export type PostApiTasksByTaskIdLogsResponses = {
    /**
     * OK
     */
    200: ResponseTaskDto;
};

export type PostApiTasksByTaskIdLogsResponse = PostApiTasksByTaskIdLogsResponses[keyof PostApiTasksByTaskIdLogsResponses];

export type CreateEventData = {
    body: RequestTimelineEventDto;
    path?: never;
    query?: never;
    url: '/api/events';
};

export type CreateEventResponses = {
    /**
     * OK
     */
    200: ResponseTimelineEventDto;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type GetEventsByCourseData = {
    body?: never;
    path: {
        courseId: number;
    };
    query?: never;
    url: '/api/events/course/{courseId}';
};

export type GetEventsByCourseResponses = {
    /**
     * OK
     */
    200: Array<ResponseTimelineEventDto>;
};

export type GetEventsByCourseResponse = GetEventsByCourseResponses[keyof GetEventsByCourseResponses];

export type DeleteEventData = {
    body?: never;
    path: {
        timelineEventId: number;
    };
    query?: never;
    url: '/api/events/{timelineEventId}';
};

export type DeleteEventResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateEventData = {
    body: RequestTimelineEventDto;
    path: {
        timelineEventId: number;
    };
    query?: never;
    url: '/api/events/{timelineEventId}';
};

export type UpdateEventResponses = {
    /**
     * OK
     */
    200: ResponseTimelineEventDto;
};

export type UpdateEventResponse = UpdateEventResponses[keyof UpdateEventResponses];

export type GetEventRequirementsData = {
    body?: never;
    path: {
        eventId: number | string;
    };
    query?: never;
    url: '/api/events/{eventId}/requirements';
};

export type GetEventRequirementsResponses = {
    /**
     * OK
     */
    200: Array<EventRequirementResDto>;
};

export type GetEventRequirementsResponse = GetEventRequirementsResponses[keyof GetEventRequirementsResponses];

export type CreateEvenetRequirementData = {
    body: EventRequirementReqDto;
    path: {
        eventId: number | string;
    };
    query?: never;
    url: '/api/events/{eventId}/requirements';
};

export type CreateEvenetRequirementResponses = {
    /**
     * OK
     */
    200: ResponseTimelineEventDto;
};

export type CreateEvenetRequirementResponse = CreateEvenetRequirementResponses[keyof CreateEvenetRequirementResponses];

export type DeleteEventRequirementData = {
    body?: never;
    path: {
        requirementId: number | string;
    };
    query?: never;
    url: '/api/events/requirements/{requirementId}';
};

export type DeleteEventRequirementResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateEventRequirementData = {
    body: EventRequirementReqDto;
    path: {
        requirementId: number | string;
    };
    query?: never;
    url: '/api/events/requirements/{requirementId}';
};

export type UpdateEventRequirementResponses = {
    /**
     * OK
     */
    200: EventRequirementResDto;
};

export type UpdateEventRequirementResponse = UpdateEventRequirementResponses[keyof UpdateEventRequirementResponses];

export type PostApiUsersSettingData = {
    body: UserSettingDto;
    path?: never;
    query?: never;
    url: '/api/users/setting';
};

export type PostApiUsersSettingResponses = {
    /**
     * OK
     */
    200: unknown;
};
