FROM python:3.11-slim
WORKDIR /app

#1. Copy danh sách thư viện
COPY requirements.txt .

# 2. Cài đặt thư viện
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]