using MapsterMapper;
using Microsoft.EntityFrameworkCore;
using SmartStudy.Server.Data;
using SmartStudy.Server.Dtos;
using SmartStudy.Server.Entities.Enums;
using SmartStudy.Server.Services.AssetLink;
using SmartStudy.Server.Services.UserService;

namespace SmartStudy.Server.Services.Semester
{
    public interface ISemesterService
    {
        Task<ResponseSemesterDto> CreateSemesterAsync(RequestSemesterDto SemesterDto);
        Task<List<ResponseSemesterDto>> GetSemestersByUserIdAsync();
        Task<ResponseSemesterDto?> GetSemesterByIdAsync(int SemesterId);
        Task<ResponseSemesterDto?> UpdateSemesterAsync(int SemesterId, RequestSemesterDto SemesterDto);
        Task<bool> DeleteSemesterAsync(int SemesterId);
        Task BulkSetupSemestersAsync(int userId, List<RequestSemesterDto> dtos);
        //System.Threading.Tasks.Task UpdateSemesterProgressAsync(int SemesterId);
    }
    public class SemesterService : ISemesterService
    {
        private readonly ApplicationDbContext _context;
        private readonly IAssetLinkService _assetLinkService;
        private readonly ICurrentUserService _currentUserService;
        private readonly IMapper _mapper;

        public SemesterService(
            ApplicationDbContext context,
            IAssetLinkService assetLinkService,
            ICurrentUserService currentUserService,
            IMapper mapper
            )
        {
            _context = context;
            _assetLinkService = assetLinkService;
            _currentUserService = currentUserService;
            _mapper = mapper;
        }

        public async Task<ResponseSemesterDto> CreateSemesterAsync(RequestSemesterDto SemesterDto)
        {
            var userId = _currentUserService.UserId;

            // Map DTO to Model
            var Semester = _mapper.Map<Entities.Semester>(SemesterDto);
            Semester.UserId = userId;

            // Name will be generated by Mapster mapping (see Mappings/SemesterMapping)

            // Gán UserId cho tất cả Course con nếu có
            if (Semester.Courses != null && Semester.Courses.Any())
            {
                foreach (var Course in Semester.Courses)
                {
                    Course.UserId = userId;
                }
            }
            // Add to DB
            await ProcessSemesterChangesAsync(Semester.UserId, list => {
                list.Add(Semester);
                _context.Semesters.Add(Semester);
            });

            // Return DTO
            return _mapper.Map<ResponseSemesterDto>(Semester);
        }

        public async Task<ResponseSemesterDto?> GetSemesterByIdAsync(int SemesterId)
        {
            var userId = _currentUserService.UserId;
            var Semester = await _context.Semesters
                .Include(p => p.Courses)
                .FirstOrDefaultAsync(p => p.Id == SemesterId);
            if (Semester == null) return null;
            _currentUserService.CheckAuthorized(Semester.UserId, nameof(Entities.Semester));
            return _mapper.Map<ResponseSemesterDto>(Semester);
        }

        public async Task<List<ResponseSemesterDto>> GetSemestersByUserIdAsync()
        {
            var userId = _currentUserService.UserId;
            var Semesters = await _context.Semesters
                .Include(p => p.Courses)
                .Where(p => p.UserId == userId)
                .OrderByDescending(p => p.StartDate)
                .ToListAsync();

            return _mapper.Map<List<ResponseSemesterDto>>(Semesters);
        }

        public async Task<ResponseSemesterDto?> UpdateSemesterAsync(int SemesterId, RequestSemesterDto SemesterDto)
        {
            var userId = _currentUserService.UserId;
            var Semester = await _context.Semesters.Include(p=>p.Courses).FirstOrDefaultAsync(p => p.Id == SemesterId);
            if (Semester == null) return null;
            
            _mapper.Map(SemesterDto, Semester); // Map đè dữ liệu mới cho Semester

            await ProcessSemesterChangesAsync(userId, list => {
                var target = list.FirstOrDefault(s => s.Id == SemesterId);
                if (target != null)
                {
                    _mapper.Map(SemesterDto, target); // Ghi đè ngày tháng mới
                }
            });

            return _mapper.Map<ResponseSemesterDto>(Semester);
        }

        public async Task<bool> DeleteSemesterAsync(int SemesterId)
        {
            var userId = _currentUserService.UserId;
            bool isDeleted = false;

            await ProcessSemesterChangesAsync(userId, list => {
                var target = list.FirstOrDefault(s => s.Id == SemesterId);
                if (target != null)
                {
                    list.Remove(target);
                    _context.Semesters.Remove(target);
                    isDeleted = true;
                }
            });

            if(isDeleted) await _assetLinkService.RemoveAssetLinkByAsync(SemesterId, AssetLinkType.Semester);
            
            return isDeleted;
        }

        private async Task ProcessSemesterChangesAsync(int userId, Action<List<Entities.Semester>> modifyListAction)
        {
            // 1. Kéo toàn bộ lên RAM
            var allSemesters = await _context.Semesters.Where(s => s.UserId == userId).ToListAsync();

            // 2. THỰC THI HÀNH ĐỘNG 
            modifyListAction(allSemesters);

            // 3. Tự động sắp xếp và đánh số lại toàn bộ
            var sorted = allSemesters.OrderBy(s => s.StartDate).ToList();
            for (int i = 0; i < sorted.Count; i++)
            {
                sorted[i].Order = i + 1;
            }

            // 4. Cú chốt: Lưu 1 lần duy nhất
            await _context.SaveChangesAsync();
        }

        public async Task BulkSetupSemestersAsync(int userId, List<RequestSemesterDto> dtos)
        {
            await ProcessSemesterChangesAsync(userId, list =>
            {
                _context.Semesters.RemoveRange(list);
                list.Clear();

                // Map list DTO sang list Entity
                var newEntities = _mapper.Map<List<Entities.Semester>>(dtos);
                foreach (var item in newEntities)
                {
                    item.UserId = userId;
                    list.Add(item);
                    _context.Semesters.Add(item);
                }
            });
        }
    }
}