// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { bulkCreateSubjects, createCourse, createEvenetRequirement, createEvent, createRoutine, createStudyPlan, createSubject, deleteApiTasksByTaskId, deleteAsset, deleteCourse, deleteEvent, deleteEventRequirement, deleteLog, deleteRoutine, deleteStudyPlan, deleteSubject, generateTasks, getApiChatSessions, getApiChatSessionsBySessionId, getApiTasksByTaskId, getAssets, getCourseById, getCoursesByStudyPlan, getEventRequirements, getEventsByCourse, getLog, getProfile, getRoutineById, getRoutines, getStudyPlanById, getStudyPlans, getSubjects, getUpcomingRoutineTasks, login, type Options, patchApiTasksByTaskIdStatus, postApiChatSessions, postApiChatSessionsBySessionIdStream, postApiTasks, postApiTasksByTaskIdLogs, postApiUsersSetting, register, updateCourse, updateEvent, updateEventRequirement, updateLog, updateRoutine, updateStudyPlan, updateSubject, updateTaskInfo, uploadAssets } from '../sdk.gen';
import type { BulkCreateSubjectsData, BulkCreateSubjectsResponse, CreateCourseData, CreateCourseResponse, CreateEvenetRequirementData, CreateEvenetRequirementResponse, CreateEventData, CreateEventResponse, CreateRoutineData, CreateRoutineResponse, CreateStudyPlanData, CreateStudyPlanResponse, CreateSubjectData, CreateSubjectResponse, DeleteApiTasksByTaskIdData, DeleteAssetData, DeleteCourseData, DeleteEventData, DeleteEventRequirementData, DeleteLogData, DeleteRoutineData, DeleteStudyPlanData, DeleteSubjectData, GenerateTasksData, GetApiChatSessionsBySessionIdData, GetApiChatSessionsData, GetApiTasksByTaskIdData, GetApiTasksByTaskIdResponse, GetAssetsData, GetAssetsResponse, GetCourseByIdData, GetCourseByIdResponse, GetCoursesByStudyPlanData, GetCoursesByStudyPlanResponse, GetEventRequirementsData, GetEventRequirementsResponse, GetEventsByCourseData, GetEventsByCourseResponse, GetLogData, GetLogResponse, GetProfileData, GetProfileResponse, GetRoutineByIdData, GetRoutineByIdResponse, GetRoutinesData, GetRoutinesResponse, GetStudyPlanByIdData, GetStudyPlanByIdResponse, GetStudyPlansData, GetStudyPlansResponse, GetSubjectsData, GetSubjectsResponse, GetUpcomingRoutineTasksData, GetUpcomingRoutineTasksResponse, LoginData, LoginResponse, PatchApiTasksByTaskIdStatusData, PatchApiTasksByTaskIdStatusResponse, PostApiChatSessionsBySessionIdStreamData, PostApiChatSessionsData, PostApiTasksByTaskIdLogsData, PostApiTasksByTaskIdLogsResponse, PostApiTasksData, PostApiTasksResponse, PostApiUsersSettingData, RegisterData, RegisterResponse, UpdateCourseData, UpdateCourseResponse, UpdateEventData, UpdateEventRequirementData, UpdateEventRequirementResponse, UpdateEventResponse, UpdateLogData, UpdateLogResponse, UpdateRoutineData, UpdateRoutineResponse, UpdateStudyPlanData, UpdateStudyPlanResponse, UpdateSubjectData, UpdateSubjectResponse, UpdateTaskInfoData, UpdateTaskInfoResponse, UploadAssetsData, UploadAssetsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAssetsQueryKey = (options?: Options<GetAssetsData>) => createQueryKey('getAssets', options);

export const getAssetsOptions = (options?: Options<GetAssetsData>) => queryOptions<GetAssetsResponse, AxiosError<DefaultError>, GetAssetsResponse, ReturnType<typeof getAssetsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAssets({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAssetsQueryKey(options)
});

export const uploadAssetsMutation = (options?: Partial<Options<UploadAssetsData>>): UseMutationOptions<UploadAssetsResponse, AxiosError<DefaultError>, Options<UploadAssetsData>> => {
    const mutationOptions: UseMutationOptions<UploadAssetsResponse, AxiosError<DefaultError>, Options<UploadAssetsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadAssets({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteAssetMutation = (options?: Partial<Options<DeleteAssetData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteAssetData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteAssetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAsset({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, AxiosError<DefaultError>, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, AxiosError<DefaultError>, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, AxiosError<DefaultError>, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, AxiosError<DefaultError>, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getProfileQueryKey = (options?: Options<GetProfileData>) => createQueryKey('getProfile', options);

export const getProfileOptions = (options?: Options<GetProfileData>) => queryOptions<GetProfileResponse, AxiosError<DefaultError>, GetProfileResponse, ReturnType<typeof getProfileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProfile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProfileQueryKey(options)
});

export const getApiChatSessionsBySessionIdQueryKey = (options: Options<GetApiChatSessionsBySessionIdData>) => createQueryKey('getApiChatSessionsBySessionId', options);

export const getApiChatSessionsBySessionIdOptions = (options: Options<GetApiChatSessionsBySessionIdData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof getApiChatSessionsBySessionIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiChatSessionsBySessionId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiChatSessionsBySessionIdQueryKey(options)
});

export const getApiChatSessionsQueryKey = (options?: Options<GetApiChatSessionsData>) => createQueryKey('getApiChatSessions', options);

export const getApiChatSessionsOptions = (options?: Options<GetApiChatSessionsData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof getApiChatSessionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiChatSessions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiChatSessionsQueryKey(options)
});

export const postApiChatSessionsMutation = (options?: Partial<Options<PostApiChatSessionsData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostApiChatSessionsData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostApiChatSessionsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiChatSessions({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiChatSessionsBySessionIdStreamMutation = (options?: Partial<Options<PostApiChatSessionsBySessionIdStreamData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostApiChatSessionsBySessionIdStreamData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostApiChatSessionsBySessionIdStreamData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiChatSessionsBySessionIdStream({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCoursesByStudyPlanQueryKey = (options: Options<GetCoursesByStudyPlanData>) => createQueryKey('getCoursesByStudyPlan', options);

export const getCoursesByStudyPlanOptions = (options: Options<GetCoursesByStudyPlanData>) => queryOptions<GetCoursesByStudyPlanResponse, AxiosError<DefaultError>, GetCoursesByStudyPlanResponse, ReturnType<typeof getCoursesByStudyPlanQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCoursesByStudyPlan({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCoursesByStudyPlanQueryKey(options)
});

export const deleteCourseMutation = (options?: Partial<Options<DeleteCourseData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteCourseData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteCourseData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteCourse({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCourseByIdQueryKey = (options: Options<GetCourseByIdData>) => createQueryKey('getCourseById', options);

export const getCourseByIdOptions = (options: Options<GetCourseByIdData>) => queryOptions<GetCourseByIdResponse, AxiosError<DefaultError>, GetCourseByIdResponse, ReturnType<typeof getCourseByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCourseById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCourseByIdQueryKey(options)
});

export const updateCourseMutation = (options?: Partial<Options<UpdateCourseData>>): UseMutationOptions<UpdateCourseResponse, AxiosError<DefaultError>, Options<UpdateCourseData>> => {
    const mutationOptions: UseMutationOptions<UpdateCourseResponse, AxiosError<DefaultError>, Options<UpdateCourseData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateCourse({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createCourseMutation = (options?: Partial<Options<CreateCourseData>>): UseMutationOptions<CreateCourseResponse, AxiosError<DefaultError>, Options<CreateCourseData>> => {
    const mutationOptions: UseMutationOptions<CreateCourseResponse, AxiosError<DefaultError>, Options<CreateCourseData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createCourse({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteLogMutation = (options?: Partial<Options<DeleteLogData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteLogData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteLogData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteLog({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getLogQueryKey = (options: Options<GetLogData>) => createQueryKey('getLog', options);

export const getLogOptions = (options: Options<GetLogData>) => queryOptions<GetLogResponse, AxiosError<DefaultError>, GetLogResponse, ReturnType<typeof getLogQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLog({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLogQueryKey(options)
});

export const updateLogMutation = (options?: Partial<Options<UpdateLogData>>): UseMutationOptions<UpdateLogResponse, AxiosError<DefaultError>, Options<UpdateLogData>> => {
    const mutationOptions: UseMutationOptions<UpdateLogResponse, AxiosError<DefaultError>, Options<UpdateLogData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateLog({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteRoutineMutation = (options?: Partial<Options<DeleteRoutineData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteRoutineData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteRoutineData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRoutine({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRoutineByIdQueryKey = (options: Options<GetRoutineByIdData>) => createQueryKey('getRoutineById', options);

export const getRoutineByIdOptions = (options: Options<GetRoutineByIdData>) => queryOptions<GetRoutineByIdResponse, AxiosError<DefaultError>, GetRoutineByIdResponse, ReturnType<typeof getRoutineByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRoutineById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRoutineByIdQueryKey(options)
});

export const updateRoutineMutation = (options?: Partial<Options<UpdateRoutineData>>): UseMutationOptions<UpdateRoutineResponse, AxiosError<DefaultError>, Options<UpdateRoutineData>> => {
    const mutationOptions: UseMutationOptions<UpdateRoutineResponse, AxiosError<DefaultError>, Options<UpdateRoutineData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateRoutine({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRoutinesQueryKey = (options?: Options<GetRoutinesData>) => createQueryKey('getRoutines', options);

export const getRoutinesOptions = (options?: Options<GetRoutinesData>) => queryOptions<GetRoutinesResponse, AxiosError<DefaultError>, GetRoutinesResponse, ReturnType<typeof getRoutinesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRoutines({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRoutinesQueryKey(options)
});

export const createRoutineMutation = (options?: Partial<Options<CreateRoutineData>>): UseMutationOptions<CreateRoutineResponse, AxiosError<DefaultError>, Options<CreateRoutineData>> => {
    const mutationOptions: UseMutationOptions<CreateRoutineResponse, AxiosError<DefaultError>, Options<CreateRoutineData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createRoutine({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const generateTasksMutation = (options?: Partial<Options<GenerateTasksData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<GenerateTasksData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<GenerateTasksData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await generateTasks({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUpcomingRoutineTasksQueryKey = (options: Options<GetUpcomingRoutineTasksData>) => createQueryKey('getUpcomingRoutineTasks', options);

export const getUpcomingRoutineTasksOptions = (options: Options<GetUpcomingRoutineTasksData>) => queryOptions<GetUpcomingRoutineTasksResponse, AxiosError<DefaultError>, GetUpcomingRoutineTasksResponse, ReturnType<typeof getUpcomingRoutineTasksQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUpcomingRoutineTasks({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUpcomingRoutineTasksQueryKey(options)
});

export const getStudyPlansQueryKey = (options?: Options<GetStudyPlansData>) => createQueryKey('getStudyPlans', options);

export const getStudyPlansOptions = (options?: Options<GetStudyPlansData>) => queryOptions<GetStudyPlansResponse, AxiosError<DefaultError>, GetStudyPlansResponse, ReturnType<typeof getStudyPlansQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStudyPlans({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStudyPlansQueryKey(options)
});

export const createStudyPlanMutation = (options?: Partial<Options<CreateStudyPlanData>>): UseMutationOptions<CreateStudyPlanResponse, AxiosError<DefaultError>, Options<CreateStudyPlanData>> => {
    const mutationOptions: UseMutationOptions<CreateStudyPlanResponse, AxiosError<DefaultError>, Options<CreateStudyPlanData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createStudyPlan({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteStudyPlanMutation = (options?: Partial<Options<DeleteStudyPlanData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteStudyPlanData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteStudyPlanData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteStudyPlan({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getStudyPlanByIdQueryKey = (options: Options<GetStudyPlanByIdData>) => createQueryKey('getStudyPlanById', options);

export const getStudyPlanByIdOptions = (options: Options<GetStudyPlanByIdData>) => queryOptions<GetStudyPlanByIdResponse, AxiosError<DefaultError>, GetStudyPlanByIdResponse, ReturnType<typeof getStudyPlanByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStudyPlanById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStudyPlanByIdQueryKey(options)
});

export const updateStudyPlanMutation = (options?: Partial<Options<UpdateStudyPlanData>>): UseMutationOptions<UpdateStudyPlanResponse, AxiosError<DefaultError>, Options<UpdateStudyPlanData>> => {
    const mutationOptions: UseMutationOptions<UpdateStudyPlanResponse, AxiosError<DefaultError>, Options<UpdateStudyPlanData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateStudyPlan({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSubjectsQueryKey = (options?: Options<GetSubjectsData>) => createQueryKey('getSubjects', options);

export const getSubjectsOptions = (options?: Options<GetSubjectsData>) => queryOptions<GetSubjectsResponse, AxiosError<DefaultError>, GetSubjectsResponse, ReturnType<typeof getSubjectsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSubjects({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSubjectsQueryKey(options)
});

export const createSubjectMutation = (options?: Partial<Options<CreateSubjectData>>): UseMutationOptions<CreateSubjectResponse, AxiosError<DefaultError>, Options<CreateSubjectData>> => {
    const mutationOptions: UseMutationOptions<CreateSubjectResponse, AxiosError<DefaultError>, Options<CreateSubjectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createSubject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const bulkCreateSubjectsMutation = (options?: Partial<Options<BulkCreateSubjectsData>>): UseMutationOptions<BulkCreateSubjectsResponse, AxiosError<DefaultError>, Options<BulkCreateSubjectsData>> => {
    const mutationOptions: UseMutationOptions<BulkCreateSubjectsResponse, AxiosError<DefaultError>, Options<BulkCreateSubjectsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await bulkCreateSubjects({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteSubjectMutation = (options?: Partial<Options<DeleteSubjectData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteSubjectData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteSubjectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteSubject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateSubjectMutation = (options?: Partial<Options<UpdateSubjectData>>): UseMutationOptions<UpdateSubjectResponse, AxiosError<DefaultError>, Options<UpdateSubjectData>> => {
    const mutationOptions: UseMutationOptions<UpdateSubjectResponse, AxiosError<DefaultError>, Options<UpdateSubjectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateSubject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiTasksMutation = (options?: Partial<Options<PostApiTasksData>>): UseMutationOptions<PostApiTasksResponse, AxiosError<DefaultError>, Options<PostApiTasksData>> => {
    const mutationOptions: UseMutationOptions<PostApiTasksResponse, AxiosError<DefaultError>, Options<PostApiTasksData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiTasks({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiTasksByTaskIdMutation = (options?: Partial<Options<DeleteApiTasksByTaskIdData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteApiTasksByTaskIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteApiTasksByTaskIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiTasksByTaskId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiTasksByTaskIdQueryKey = (options: Options<GetApiTasksByTaskIdData>) => createQueryKey('getApiTasksByTaskId', options);

export const getApiTasksByTaskIdOptions = (options: Options<GetApiTasksByTaskIdData>) => queryOptions<GetApiTasksByTaskIdResponse, AxiosError<DefaultError>, GetApiTasksByTaskIdResponse, ReturnType<typeof getApiTasksByTaskIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiTasksByTaskId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiTasksByTaskIdQueryKey(options)
});

export const updateTaskInfoMutation = (options?: Partial<Options<UpdateTaskInfoData>>): UseMutationOptions<UpdateTaskInfoResponse, AxiosError<DefaultError>, Options<UpdateTaskInfoData>> => {
    const mutationOptions: UseMutationOptions<UpdateTaskInfoResponse, AxiosError<DefaultError>, Options<UpdateTaskInfoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateTaskInfo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const patchApiTasksByTaskIdStatusMutation = (options?: Partial<Options<PatchApiTasksByTaskIdStatusData>>): UseMutationOptions<PatchApiTasksByTaskIdStatusResponse, AxiosError<DefaultError>, Options<PatchApiTasksByTaskIdStatusData>> => {
    const mutationOptions: UseMutationOptions<PatchApiTasksByTaskIdStatusResponse, AxiosError<DefaultError>, Options<PatchApiTasksByTaskIdStatusData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchApiTasksByTaskIdStatus({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiTasksByTaskIdLogsMutation = (options?: Partial<Options<PostApiTasksByTaskIdLogsData>>): UseMutationOptions<PostApiTasksByTaskIdLogsResponse, AxiosError<DefaultError>, Options<PostApiTasksByTaskIdLogsData>> => {
    const mutationOptions: UseMutationOptions<PostApiTasksByTaskIdLogsResponse, AxiosError<DefaultError>, Options<PostApiTasksByTaskIdLogsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiTasksByTaskIdLogs({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createEventMutation = (options?: Partial<Options<CreateEventData>>): UseMutationOptions<CreateEventResponse, AxiosError<DefaultError>, Options<CreateEventData>> => {
    const mutationOptions: UseMutationOptions<CreateEventResponse, AxiosError<DefaultError>, Options<CreateEventData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createEvent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEventsByCourseQueryKey = (options: Options<GetEventsByCourseData>) => createQueryKey('getEventsByCourse', options);

export const getEventsByCourseOptions = (options: Options<GetEventsByCourseData>) => queryOptions<GetEventsByCourseResponse, AxiosError<DefaultError>, GetEventsByCourseResponse, ReturnType<typeof getEventsByCourseQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEventsByCourse({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEventsByCourseQueryKey(options)
});

export const deleteEventMutation = (options?: Partial<Options<DeleteEventData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteEventData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteEventData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteEvent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateEventMutation = (options?: Partial<Options<UpdateEventData>>): UseMutationOptions<UpdateEventResponse, AxiosError<DefaultError>, Options<UpdateEventData>> => {
    const mutationOptions: UseMutationOptions<UpdateEventResponse, AxiosError<DefaultError>, Options<UpdateEventData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateEvent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEventRequirementsQueryKey = (options: Options<GetEventRequirementsData>) => createQueryKey('getEventRequirements', options);

export const getEventRequirementsOptions = (options: Options<GetEventRequirementsData>) => queryOptions<GetEventRequirementsResponse, AxiosError<DefaultError>, GetEventRequirementsResponse, ReturnType<typeof getEventRequirementsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEventRequirements({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEventRequirementsQueryKey(options)
});

export const createEvenetRequirementMutation = (options?: Partial<Options<CreateEvenetRequirementData>>): UseMutationOptions<CreateEvenetRequirementResponse, AxiosError<DefaultError>, Options<CreateEvenetRequirementData>> => {
    const mutationOptions: UseMutationOptions<CreateEvenetRequirementResponse, AxiosError<DefaultError>, Options<CreateEvenetRequirementData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createEvenetRequirement({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteEventRequirementMutation = (options?: Partial<Options<DeleteEventRequirementData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteEventRequirementData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteEventRequirementData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteEventRequirement({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateEventRequirementMutation = (options?: Partial<Options<UpdateEventRequirementData>>): UseMutationOptions<UpdateEventRequirementResponse, AxiosError<DefaultError>, Options<UpdateEventRequirementData>> => {
    const mutationOptions: UseMutationOptions<UpdateEventRequirementResponse, AxiosError<DefaultError>, Options<UpdateEventRequirementData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateEventRequirement({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiUsersSettingMutation = (options?: Partial<Options<PostApiUsersSettingData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostApiUsersSettingData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostApiUsersSettingData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiUsersSetting({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
