// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartStudy.Server.Data;

#nullable disable

namespace SmartStudy.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260415135006_PhaseArchitecture_Update")]
    partial class PhaseArchitecture_Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "a1b2c3d4-0001-0000-0000-000000000000",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "a1b2c3d4-0002-0000-0000-000000000000",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.AcademicTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TermNumber")
                        .HasColumnType("integer")
                        .HasColumnName("term_number");

                    b.HasKey("Id")
                        .HasName("pk_academic_terms");

                    b.ToTable("academic_terms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Học kỳ I",
                            TermNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Học kỳ II",
                            TermNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Học kỳ III",
                            TermNumber = 3
                        });
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnName("end_year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.HasKey("Id")
                        .HasName("pk_academic_years");

                    b.ToTable("academic_years", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2010,
                            EndYear = 2011,
                            Name = "Niên khóa 2010 - 2011",
                            StartYear = 2010
                        },
                        new
                        {
                            Id = 2011,
                            EndYear = 2012,
                            Name = "Niên khóa 2011 - 2012",
                            StartYear = 2011
                        },
                        new
                        {
                            Id = 2012,
                            EndYear = 2013,
                            Name = "Niên khóa 2012 - 2013",
                            StartYear = 2012
                        },
                        new
                        {
                            Id = 2013,
                            EndYear = 2014,
                            Name = "Niên khóa 2013 - 2014",
                            StartYear = 2013
                        },
                        new
                        {
                            Id = 2014,
                            EndYear = 2015,
                            Name = "Niên khóa 2014 - 2015",
                            StartYear = 2014
                        },
                        new
                        {
                            Id = 2015,
                            EndYear = 2016,
                            Name = "Niên khóa 2015 - 2016",
                            StartYear = 2015
                        },
                        new
                        {
                            Id = 2016,
                            EndYear = 2017,
                            Name = "Niên khóa 2016 - 2017",
                            StartYear = 2016
                        },
                        new
                        {
                            Id = 2017,
                            EndYear = 2018,
                            Name = "Niên khóa 2017 - 2018",
                            StartYear = 2017
                        },
                        new
                        {
                            Id = 2018,
                            EndYear = 2019,
                            Name = "Niên khóa 2018 - 2019",
                            StartYear = 2018
                        },
                        new
                        {
                            Id = 2019,
                            EndYear = 2020,
                            Name = "Niên khóa 2019 - 2020",
                            StartYear = 2019
                        },
                        new
                        {
                            Id = 2020,
                            EndYear = 2021,
                            Name = "Niên khóa 2020 - 2021",
                            StartYear = 2020
                        },
                        new
                        {
                            Id = 2021,
                            EndYear = 2022,
                            Name = "Niên khóa 2021 - 2022",
                            StartYear = 2021
                        },
                        new
                        {
                            Id = 2022,
                            EndYear = 2023,
                            Name = "Niên khóa 2022 - 2023",
                            StartYear = 2022
                        },
                        new
                        {
                            Id = 2023,
                            EndYear = 2024,
                            Name = "Niên khóa 2023 - 2024",
                            StartYear = 2023
                        },
                        new
                        {
                            Id = 2024,
                            EndYear = 2025,
                            Name = "Niên khóa 2024 - 2025",
                            StartYear = 2024
                        },
                        new
                        {
                            Id = 2025,
                            EndYear = 2026,
                            Name = "Niên khóa 2025 - 2026",
                            StartYear = 2025
                        },
                        new
                        {
                            Id = 2026,
                            EndYear = 2027,
                            Name = "Niên khóa 2026 - 2027",
                            StartYear = 2026
                        },
                        new
                        {
                            Id = 2027,
                            EndYear = 2028,
                            Name = "Niên khóa 2027 - 2028",
                            StartYear = 2027
                        },
                        new
                        {
                            Id = 2028,
                            EndYear = 2029,
                            Name = "Niên khóa 2028 - 2029",
                            StartYear = 2028
                        },
                        new
                        {
                            Id = 2029,
                            EndYear = 2030,
                            Name = "Niên khóa 2029 - 2030",
                            StartYear = 2029
                        },
                        new
                        {
                            Id = 2030,
                            EndYear = 2031,
                            Name = "Niên khóa 2030 - 2031",
                            StartYear = 2030
                        },
                        new
                        {
                            Id = 2031,
                            EndYear = 2032,
                            Name = "Niên khóa 2031 - 2032",
                            StartYear = 2031
                        },
                        new
                        {
                            Id = 2032,
                            EndYear = 2033,
                            Name = "Niên khóa 2032 - 2033",
                            StartYear = 2032
                        },
                        new
                        {
                            Id = 2033,
                            EndYear = 2034,
                            Name = "Niên khóa 2033 - 2034",
                            StartYear = 2033
                        },
                        new
                        {
                            Id = 2034,
                            EndYear = 2035,
                            Name = "Niên khóa 2034 - 2035",
                            StartYear = 2034
                        },
                        new
                        {
                            Id = 2035,
                            EndYear = 2036,
                            Name = "Niên khóa 2035 - 2036",
                            StartYear = 2035
                        },
                        new
                        {
                            Id = 2036,
                            EndYear = 2037,
                            Name = "Niên khóa 2036 - 2037",
                            StartYear = 2036
                        },
                        new
                        {
                            Id = 2037,
                            EndYear = 2038,
                            Name = "Niên khóa 2037 - 2038",
                            StartYear = 2037
                        },
                        new
                        {
                            Id = 2038,
                            EndYear = 2039,
                            Name = "Niên khóa 2038 - 2039",
                            StartYear = 2038
                        },
                        new
                        {
                            Id = 2039,
                            EndYear = 2040,
                            Name = "Niên khóa 2039 - 2040",
                            StartYear = 2039
                        },
                        new
                        {
                            Id = 2040,
                            EndYear = 2041,
                            Name = "Niên khóa 2040 - 2041",
                            StartYear = 2040
                        });
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("public_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_assets_user_id");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.AssetLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("LinkedId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_id");

                    b.Property<string>("LinkedType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("linked_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asset_links");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_asset_links_asset_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asset_links_user_id");

                    b.ToTable("asset_links", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonElement?>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_chat_messages_session_id");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.ChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_sessions");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_chat_sessions_course_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_sessions_user_id");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<double?>("FinalScore")
                        .HasColumnType("double precision")
                        .HasColumnName("final_score");

                    b.Property<string>("Goal")
                        .HasColumnType("text")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("StudyPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("study_plan_id");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<double?>("TargetScore")
                        .HasColumnType("double precision")
                        .HasColumnName("target_score");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("StudyPlanId")
                        .HasDatabaseName("ix_courses_study_plan_id");

                    b.HasIndex("Name", "StudyPlanId")
                        .IsUnique()
                        .HasDatabaseName("ix_courses_name_study_plan_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("SubjectId", "StudyPlanId")
                        .IsUnique()
                        .HasDatabaseName("ix_courses_subject_id_study_plan_id")
                        .HasFilter("subject_id IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.LogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualDuration")
                        .HasColumnType("integer")
                        .HasColumnName("actual_duration");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("ComprehensionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("comprehension_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DifficultyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty_level");

                    b.Property<float?>("EarnedValue")
                        .HasColumnType("real")
                        .HasColumnName("earned_value");

                    b.Property<int?>("EventRequirementId")
                        .HasColumnType("integer")
                        .HasColumnName("event_requirement_id");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    b.Property<DateTime?>("TimerEndAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timer_end_at");

                    b.Property<DateTime?>("TimerStartAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timer_start_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_logs");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_logs_task_id");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date_time");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_day");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_phases");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_phases_course_id");

                    b.ToTable("phases", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.PlanTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int?>("SourcePlanId")
                        .HasColumnType("integer")
                        .HasColumnName("source_plan_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plan_templates");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_plan_templates_created_by_id");

                    b.HasIndex("SourcePlanId")
                        .HasDatabaseName("ix_plan_templates_source_plan_id");

                    b.ToTable("plan_templates", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Instructor")
                        .HasColumnType("text")
                        .HasColumnName("instructor");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("PhaseId")
                        .HasColumnType("integer")
                        .HasColumnName("phase_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<int?>("StudyPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("study_plan_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_routines");

                    b.HasIndex("PhaseId")
                        .HasDatabaseName("ix_routines_phase_id");

                    b.HasIndex("StudyPlanId")
                        .HasDatabaseName("ix_routines_study_plan_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_routines_user_id");

                    b.HasIndex("Name", "PhaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_routines_name_phase_id")
                        .HasFilter("deleted_at IS NULL AND phase_id IS NOT NULL");

                    b.HasIndex("Name", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_routines_name_user_id")
                        .HasFilter("deleted_at IS NULL AND phase_id IS NULL");

                    b.ToTable("routines", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int?>("RoutineId")
                        .HasColumnType("integer")
                        .HasColumnName("routine_id");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.HasIndex("RoutineId")
                        .HasDatabaseName("ix_schedules_routine_id");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.StudentInfo", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("AdmissionYear")
                        .HasColumnType("integer")
                        .HasColumnName("admission_year");

                    b.Property<string>("Cohort")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cohort");

                    b.Property<string>("Major")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("major");

                    b.Property<string>("University")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("university");

                    b.HasKey("UserId")
                        .HasName("pk_student_infos");

                    b.ToTable("student_infos", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.StudyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actual_end_date");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actual_start_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.Property<int?>("TermId")
                        .HasColumnType("integer")
                        .HasColumnName("term_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("YearId")
                        .HasColumnType("integer")
                        .HasColumnName("year_id");

                    b.HasKey("Id")
                        .HasName("pk_study_plans");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_study_plans_template_id");

                    b.HasIndex("TermId")
                        .HasDatabaseName("ix_study_plans_term_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_study_plans_user_id");

                    b.HasIndex("YearId")
                        .HasDatabaseName("ix_study_plans_year_id");

                    b.ToTable("study_plans", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Credits")
                        .HasColumnType("integer")
                        .HasColumnName("credits");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subjects");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_subjects_user_id");

                    b.HasIndex("Name", "Type", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_subjects_name_type_user_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date_time");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PhaseId")
                        .HasColumnType("integer")
                        .HasColumnName("phase_id");

                    b.Property<int?>("RoutineId")
                        .HasColumnType("integer")
                        .HasColumnName("routine_id");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("status_updated_at");

                    b.Property<int?>("StudyPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("study_plan_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("PhaseId")
                        .HasDatabaseName("ix_tasks_phase_id");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_tasks_schedule_id");

                    b.HasIndex("StudyPlanId")
                        .HasDatabaseName("ix_tasks_study_plan_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tasks_user_id");

                    b.HasIndex("RoutineId", "ScheduleId", "StartDateTime")
                        .IsUnique()
                        .HasDatabaseName("ix_tasks_routine_id_schedule_id_start_date_time");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("SmartStudy.Server.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Asset", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.AssetLink", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.Asset", "Asset")
                        .WithMany("AssetLinks")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_links_assets_asset_id");

                    b.HasOne("SmartStudy.Server.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_links_users_user_id");

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.ChatMessage", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.ChatSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_chat_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.ChatSession", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.Course", "Course")
                        .WithMany("ChatSessions")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("fk_chat_sessions_courses_course_id");

                    b.HasOne("SmartStudy.Server.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_sessions_users_user_id");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Course", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.StudyPlan", "StudyPlan")
                        .WithMany("Courses")
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courses_study_plans_study_plan_id");

                    b.HasOne("SmartStudy.Server.Entities.Subject", "Subject")
                        .WithMany("Courses")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("fk_courses_subjects_subject_id");

                    b.Navigation("StudyPlan");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.LogItem", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.TaskItem", "Task")
                        .WithMany("Logs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_logs_tasks_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Phase", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.Course", "Course")
                        .WithMany("Phases")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_phases_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.PlanTemplate", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_plan_templates_users_created_by_id");

                    b.HasOne("SmartStudy.Server.Entities.StudyPlan", "SourcePlan")
                        .WithMany()
                        .HasForeignKey("SourcePlanId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_plan_templates_study_plans_source_plan_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("SourcePlan");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.RefreshToken", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Routine", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.Phase", "Phase")
                        .WithMany("Routines")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_routines_phases_phase_id");

                    b.HasOne("SmartStudy.Server.Entities.StudyPlan", "StudyPlan")
                        .WithMany()
                        .HasForeignKey("StudyPlanId")
                        .HasConstraintName("fk_routines_study_plans_study_plan_id");

                    b.HasOne("SmartStudy.Server.Entities.User", "User")
                        .WithMany("Routines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routines_users_user_id");

                    b.Navigation("Phase");

                    b.Navigation("StudyPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Schedule", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.Routine", "Routine")
                        .WithMany("Schedules")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_schedules_routines_routine_id");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.StudentInfo", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.User", "User")
                        .WithOne("StudentInfo")
                        .HasForeignKey("SmartStudy.Server.Entities.StudentInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_infos_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.StudyPlan", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.PlanTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_study_plans_plan_templates_template_id");

                    b.HasOne("SmartStudy.Server.Entities.AcademicTerm", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .HasConstraintName("fk_study_plans_academic_terms_term_id");

                    b.HasOne("SmartStudy.Server.Entities.User", "User")
                        .WithMany("StudyPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_study_plans_users_user_id");

                    b.HasOne("SmartStudy.Server.Entities.AcademicYear", "Year")
                        .WithMany()
                        .HasForeignKey("YearId")
                        .HasConstraintName("fk_study_plans_academic_years_year_id");

                    b.Navigation("Template");

                    b.Navigation("Term");

                    b.Navigation("User");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Subject", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.User", "User")
                        .WithMany("Subjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subjects_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.TaskItem", b =>
                {
                    b.HasOne("SmartStudy.Server.Entities.Phase", "Phase")
                        .WithMany("Tasks")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tasks_phases_phase_id");

                    b.HasOne("SmartStudy.Server.Entities.Routine", "Routine")
                        .WithMany("Tasks")
                        .HasForeignKey("RoutineId")
                        .HasConstraintName("fk_tasks_routines_routine_id");

                    b.HasOne("SmartStudy.Server.Entities.Schedule", "Schedule")
                        .WithMany("Tasks")
                        .HasForeignKey("ScheduleId")
                        .HasConstraintName("fk_tasks_schedules_schedule_id");

                    b.HasOne("SmartStudy.Server.Entities.StudyPlan", "StudyPlan")
                        .WithMany()
                        .HasForeignKey("StudyPlanId")
                        .HasConstraintName("fk_tasks_study_plans_study_plan_id");

                    b.HasOne("SmartStudy.Server.Entities.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_users_user_id");

                    b.Navigation("Phase");

                    b.Navigation("Routine");

                    b.Navigation("Schedule");

                    b.Navigation("StudyPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Asset", b =>
                {
                    b.Navigation("AssetLinks");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Course", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("Phases");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Phase", b =>
                {
                    b.Navigation("Routines");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Routine", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Schedule", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.StudyPlan", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.Subject", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.TaskItem", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("SmartStudy.Server.Entities.User", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Routines");

                    b.Navigation("StudentInfo")
                        .IsRequired();

                    b.Navigation("StudyPlans");

                    b.Navigation("Subjects");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
